### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/pandoc-feedstock#18] opened 2017-08-29 15:08 UTC
Hello,

When I install `pandoc` with `conda env create -f pandoc-conda-forge.yml`, being `pandoc-conda-forge.yml` the following environment file:
```
name: pandoc

channels:
- conda-forge

dependencies:
- pandoc
```

I get:
```
$ pandoc --version
Segmentation fault
```

However, when I do the same with the `defaults` channel:
```
name: pandoc

channels:
- defaults

dependencies:
- pandoc
```

It works:
```
pandoc 1.15.0.6
Compiled with texmath 0.8.3, highlighting-kate 0.6.
Syntax highlighting is supported for the following languages:
    abc, actionscript, ada, agda, apache, asn1, asp, awk, bash, bibtex, boo, c,
    changelog, clojure, cmake, coffee, coldfusion, commonlisp, cpp, cs, css,
    curry, d, diff, djangotemplate, dockerfile, dot, doxygen, doxygenlua, dtd,
    eiffel, email, erlang, fasm, fortran, fsharp, gcc, glsl, gnuassembler, go,
    haskell, haxe, html, idris, ini, isocpp, java, javadoc, javascript, json,
    jsp, julia, kotlin, latex, lex, lilypond, literatecurry, literatehaskell,
    lua, m4, makefile, mandoc, markdown, mathematica, matlab, maxima, mediawiki,
    metafont, mips, modelines, modula2, modula3, monobasic, nasm, noweb,
    objectivec, objectivecpp, ocaml, octave, opencl, pascal, perl, php, pike,
    postscript, prolog, pure, python, r, relaxng, relaxngcompact, rest, rhtml,
    roff, ruby, rust, scala, scheme, sci, sed, sgml, sql, sqlmysql,
    sqlpostgresql, tcl, tcsh, texinfo, verilog, vhdl, xml, xorg, xslt, xul,
    yacc, yaml, zsh
Default user data directory: /ifs/home/sebastian/.pandoc
Copyright (C) 2006-2015 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Could you please let me know why?

Many thanks in advance,
Sebastian

**Comment by janschulz** [comment] 2017-08-29 15:46
I tried to reproduce:
```bash
λ conda create -n pandoc_test -c conda-forge pandoc
[...]

λ source activate pandoc_test

(conda:pandoc_test) λ which pandoc                                                 
/home/js/.binaries/miniconda3/envs/pandoc_test/bin/pandoc

(conda:pandoc_test) λ ldd /home/js/.binaries/miniconda3/envs/pandoc_test/bin/pandoc

	linux-vdso.so.1 =>  (0x00007ffd80971000)
	libz.so.1 => /home/js/.binaries/miniconda3/envs/pandoc_test/bin/../lib/libz.so.1 (0x00007f6546ac6000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f654689b000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f6546698000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6546494000)
	libgmp.so.10 => /home/js/.binaries/miniconda3/envs/pandoc_test/bin/../lib/libgmp.so.10 (0x00007f65461df000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6545ed4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6545cbd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f65458f6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f65456d8000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c4e2d16000)

(conda:pandoc_test) λ pandoc --version                                             
pandoc 1.19.2
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.2
Default user data directory: /home/js/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

(conda:pandoc_test) λ conda list                                                   
# packages in environment at /home/js/.binaries/miniconda3/envs/pandoc_test:
#
gmp                       6.1.2                         0    conda-forge
pandoc                    1.19.2                        0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

Could you do a similar test (activate and at least the `ldd` and `conda list` line)?

**Comment by janschulz** [comment] 2017-08-29 15:47
And BTW: which OS? Linux/Windows/Mac?

**Comment by sebastian-luna-valero** [comment] 2017-08-29 16:01
Thanks @janschulz 

I am using Red Hat Enterprise Linux 6. Here is the requested info:
```
$ conda create -n pandoc_test -c conda-forge pandoc
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /tmp/conda/i1/envs/pandoc_test:

The following NEW packages will be INSTALLED:

    gmp:    6.1.2-0  conda-forge
    pandoc: 1.19.2-0 conda-forge
    zlib:   1.2.11-0 conda-forge

Proceed ([y]/n)? y

gmp-6.1.2-0.ta 100% |#############################################################################################################################################################################################| Time: 0:00:00 698.73 kB/s
zlib-1.2.11-0. 100% |#############################################################################################################################################################################################| Time: 0:00:00   1.18 MB/s
pandoc-1.19.2- 100% |#############################################################################################################################################################################################| Time: 0:00:10   1.75 MB/s
#
# To activate this environment, use:
# > source activate pandoc_test
#
# To deactivate this environment, use:
# > source deactivate pandoc_test
#

$ source activate pandoc_test

$ (pandoc_test) which pandoc
/tmp/conda/i1/envs/pandoc_test/bin/pandoc

$ (pandoc_test) ldd /tmp/conda/i1/envs/pandoc_test/bin/pandoc
	linux-vdso.so.1 =>  (0x00007ffc61f71000)
	libz.so.1 => /tmp/conda/i1/envs/pandoc_test/bin/../lib/libz.so.1 (0x00007f8d79ca8000)
	librt.so.1 => /lib64/librt.so.1 (0x000000311ca00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x000000312c000000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000311c600000)
	libgmp.so.10 => /tmp/conda/i1/envs/pandoc_test/bin/../lib/libgmp.so.10 (0x00007f8d799cd000)
	libm.so.6 => /lib64/libm.so.6 (0x000000311be00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003122200000)
	libc.so.6 => /lib64/libc.so.6 (0x000000311ba00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000311c200000)
	/lib64/ld-linux-x86-64.so.2 (0x000000311b600000)

$ (pandoc_test) pandoc --version
Segmentation fault

$ (pandoc_test) conda list
# packages in environment at /tmp/conda/i1/envs/pandoc_test:
#
gmp                       6.1.2                         0    conda-forge
pandoc                    1.19.2                        0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by janschulz** [comment] 2017-08-29 17:24
Ok, it's not a missing symbol then :-(

I've actually no real clue what to do here. The difference between defaults and conda-forge sems to be the version. We basically only download the deb and unpack it. So doing that should fail on your system as well with the 1.19.2 version from https://github.com/jgm/pandoc/releases That would then mean that there is a difference between your Red Hat system and my Ubuntu 17.04 based system and you can't move the files over anymore :-(

CC. @conda-forge/core Has anyone of you seen such a problem? Same packages work on Ubuntu, but not on Red Hat?

**Comment by ocefpaf** [comment] 2017-08-29 17:33
> CC. @conda-forge/core Has anyone of you seen such a problem? Same packages work on Ubuntu, but not on Red Hat?

I cannot reproduce the `Segmentation fault` in my system.
`openSUSE 42.3 (x86_64) 4.4.79-19-default x86_64`


Can you try the oldest version (1.16.0.2) available in conda-forge?

**Comment by sebastian-luna-valero** [comment] 2017-08-30 07:30
Thanks both. `pandoc=1.16.0.2` works on my system. Please see the output below.

```
$ conda create -n pandoc_test -c conda-forge pandoc=1.16.0.2
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /tmp/conda/i1/envs/pandoc_test:

The following NEW packages will be INSTALLED:

    gmp:    6.1.2-0    conda-forge
    pandoc: 1.16.0.2-0 conda-forge
    zlib:   1.2.11-0   conda-forge

Proceed ([y]/n)? y

gmp-6.1.2-0.ta 100% |#############################################################################################################################################################################################| Time: 0:00:01 668.39 kB/s
zlib-1.2.11-0. 100% |#############################################################################################################################################################################################| Time: 0:00:00   1.17 MB/s
pandoc-1.16.0. 100% |#############################################################################################################################################################################################| Time: 0:00:06   2.61 MB/s
#
# To activate this environment, use:
# > source activate pandoc_test
#
# To deactivate this environment, use:
# > source deactivate pandoc_test
#

$ source /tmp/conda/i1/bin/activate pandoc_test

$ (pandoc_test) which pandoc
/tmp/conda/i1/envs/pandoc_test/bin/pandoc

$ (pandoc_test) pandoc --version
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
Syntax highlighting is supported for the following languages:
    abc, actionscript, ada, agda, apache, asn1, asp, awk, bash, bibtex, boo, c,
    changelog, clojure, cmake, coffee, coldfusion, commonlisp, cpp, cs, css,
    curry, d, diff, djangotemplate, dockerfile, dot, doxygen, doxygenlua, dtd,
    eiffel, email, erlang, fasm, fortran, fsharp, gcc, glsl, gnuassembler, go,
    haskell, haxe, html, idris, ini, isocpp, java, javadoc, javascript, json,
    jsp, julia, kotlin, latex, lex, lilypond, literatecurry, literatehaskell,
    llvm, lua, m4, makefile, mandoc, markdown, mathematica, matlab, maxima,
    mediawiki, metafont, mips, modelines, modula2, modula3, monobasic, nasm,
    noweb, objectivec, objectivecpp, ocaml, octave, opencl, pascal, perl, php,
    pike, postscript, prolog, pure, python, r, relaxng, relaxngcompact, rest,
    rhtml, roff, ruby, rust, scala, scheme, sci, sed, sgml, sql, sqlmysql,
    sqlpostgresql, tcl, tcsh, texinfo, verilog, vhdl, xml, xorg, xslt, xul,
    yacc, yaml, zsh
Default user data directory: /ifs/home/sebastian/.pandoc
Copyright (C) 2006-2015 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ (pandoc_test) ldd /tmp/conda/i1/envs/pandoc_test/bin/pandoc
	linux-vdso.so.1 =>  (0x00007fff98117000)
	libz.so.1 => /tmp/conda/i1/envs/pandoc_test/bin/../lib/libz.so.1 (0x00007fba84556000)
	librt.so.1 => /lib64/librt.so.1 (0x000000311ca00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x000000312c000000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000311c600000)
	libgmp.so.10 => /tmp/conda/i1/envs/pandoc_test/bin/../lib/libgmp.so.10 (0x00007fba8427b000)
	libm.so.6 => /lib64/libm.so.6 (0x000000311be00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003122200000)
	libc.so.6 => /lib64/libc.so.6 (0x000000311ba00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000311c200000)
	/lib64/ld-linux-x86-64.so.2 (0x000000311b600000)
```

**Comment by ocefpaf** [comment] 2017-10-31 10:04
@sebastian-luna-valero it seems there is nothing we can do for you here b/c of he re-packaging. I'm closing this for now but please feel free to add your experiences here so others may find that information too.

**Closed by ocefpaf** 2017-10-31 10:04 UTC
